
## Print this to confirm loading of the custom profile.

cat("Loading USER=Kevin Williams custom IBD SLIDESHOW .Rprofile  ")
load(file=".RData")
options(warn=-1)
#dev.set(2)

.First <- function(){
	
  
  options(gsubfn.engine = "R")
  suppressMessages(library(gsubfn))
  suppressMessages(library(proto))
  suppressMessages(library(sqldf))
  
    suppressMessages(library(pacman))
    suppressMessages(library(broom))
    suppressMessages(library(dplyr))
    suppressMessages(library(haven))
    suppressMessages(library(openxlsx))
    suppressMessages(library(xlsx))
    suppressMessages(library(readxl))
    suppressMessages(library(emmeans))
    suppressMessages(library(lubridate))
    suppressMessages(library(tidyverse))
    suppressMessages(library(tidyr))
    suppressMessages(library(sjPlot))
    suppressMessages(library(lmerTest))
    suppressMessages(library(lme4))
    suppressMessages(library(ggplot2))
    suppressMessages(library(ggtext))
    suppressMessages(library(ggforce))
    suppressMessages(library(gghighlight))
    suppressMessages(library(ggrepel))
    suppressMessages(library(ggspatial))
    suppressMessages(library(GGally))
    suppressMessages(library(sf))
    suppressMessages(library(stargazer))
    suppressMessages(library(rnaturalearth))
    suppressMessages(library(rnaturalearthdata))
    suppressMessages(library(patchwork))
    suppressMessages(library(magrittr))
    suppressMessages(library(corrplot))
    suppressMessages(library(psych))
    suppressMessages(library(candisc))
    suppressMessages(library(textreg))
    suppressMessages(library(reshape2))
    suppressMessages(library(multcompView))
    suppressMessages(library(modelsummary))
    suppressMessages(library(data.table))
    suppressMessages(library(jtools))
    suppressMessages(library(epitools))
    suppressMessages(library(CCA))
    suppressMessages(library(CCP))
    suppressMessages(library(openxlsx))
    suppressMessages(library(gt))
    suppressMessages(library(kableExtra))
    suppressMessages(library(formattable))
    suppressMessages(library(apaTables))
    suppressMessages(library(Hmisc))
    suppressMessages(library(gtsummary))
    suppressMessages(library(metan))
    suppressMessages(library(skimr))
    suppressMessages(library(knitr))
    suppressMessages(library(rmarkdown))
    suppressMessages(library(gmodels))
    suppressMessages(library(tables))
    suppressMessages(library(MultinomialCI))
    suppressMessages(library(DT))
    suppressMessages(library(xaringan))
    suppressMessages(library(xaringanthemer))
    suppressMessages(library(leaflet))
    suppressMessages(library(vroom))
    suppressMessages(library(tidylog))
    
    
    suppressMessages(detach("package:dplyr", unload=F))
    suppressMessages(detach("package:broom", unload=F))
    suppressMessages(library(dplyr))
    suppressMessages(library(broom))

    
    source('~/Documents/R/Custom Functions/eov.ttest.R')
    source('~/Documents/R/Custom Functions/ttest.summary.data.R')
 
 cat("\nWelcome at", date(), "\nLoaded requested packages and dependencies successfully!\nEnjoy programming in R, Kevin!\n")
 }
 


